from research_helpers import Batch
b=Batch(37)
for lang,words in [('Malvi','gyāra|igyāre|gyare'),('Nimadi','gyāra|gyara|gyārā'),('Bagheli','egyare|gyare|igyare')]:
 b.add(lang,'eleven',words,'2485','CDIAL 2485 ekādaśa gives Prakrit egārasa, Hindi igārah, Old Gujarati igyāra, Gujarati agyār and the Kotgarhi addendum’s gyāra. Loss of the initial vowel and the -dasa→-rasa→-rah/-ra history are supported within the full numeral family; '+('Bagheli e-vowels/final -e remain qualified local variants.' if lang=='Bagheli' else 'the source’s final-vowel variants are retained as numeral forms.'),tier='qualified' if lang=='Bagheli' else 'straightforward')
for lang,words in [('Malvi','bāra|bāre|bārā'),('Nimadi','bāra|bārā'),('Bagheli','berə|bara|baṛe')]:
 b.add(lang,'twelve',words,'6658','CDIAL 6658.1 dvādaśa gives Prakrit bārasa/bāraha, Awadhi/Hindi/Old Marwari bārā, Bhojpuri bārē and Gujarati bār. The initial b- selects the first branch, not duvādaśa (section 2); '+('Bagheli e-vowels and ṛ in baṛe require local review.' if lang=='Bagheli' else 'loss of medial s/h and the final-vowel variants are directly supported.'),tier='qualified' if lang=='Bagheli' else 'straightforward',locator='6658.1')
b.add('Malvi','evening/afternoon','sānj|sañj|sanjā|sañja','12918','CDIAL 12918 saṃdhyā ‘twilight’ gives Pali sañjhā, Hindi sā̃j(h), Gujarati sā̃j and Konkani sā̃ñja ‘evening’. The source’s combined evening/afternoon label is retained; deaspiration and final -a fit the regional family, without equating afternoon and twilight in every context.',tier='qualified')
b.add('Malvi','evening/afternoon','sañc|hānc|hāñj|sānc|hãs','12918','CDIAL 12918 gives Hindi sā̃j(h), Gujarati sā̃j and a Kumaoni sā̃s comparison from *sā̃z. The h-initial and voiceless c/s survey forms are a qualified extension of this family: the source has independent s/h correspondences, but final devoicing/frication and each exact locality still require review; hāsika/hajka with additional suffixes are excluded.',tier='qualified')
b.add('Bagheli','evening/afternoon','seṇja|saṇj|ceṇja','12918','CDIAL 12918 supplies the sañjhā/sā̃j evening family through Prakrit saṃjhā and Hindi sā̃j(h). Bagheli e-vowels, retroflex nasal notation and initial c in ceṇja remain qualified local features; the source’s combined evening/afternoon label is preserved.',tier='qualified')
b.add('Bagheli','evening/afternoon','seṇche|sāḍž|seṇḍiya','12918','These are qualified candidates for CDIAL 12918 saṃdhyā beside the survey’s seṇja/saṇj and the primary Hindi sā̃j(h). The changed affricate/stop sequences, aspiration and -iya ending are not demonstrated by the primary article for Bagheli and need dialect review; no silent transcription normalization is proposed.',tier='qualified')
b.save()
