from research_helpers import Batch
b=Batch(31)
for lang,words in [('Malvi','sir'),('Nimadi','sir'),('Bagheli','sir|ser')]:
 b.add(lang,'head',words,'12452','CDIAL 12452 explicitly gives Pali/Prakrit sira, Maithili and Awadhi sir, Hindi sir, Gujarati sir/sar and Marathi śir. This is the śiras family with final-s loss, not the separate śīrṣa head; '+('Bagheli ser has a qualified vowel difference from sir.' if lang=='Bagheli' else 'the attested sir and meaning match directly.'),tier='qualified' if lang=='Bagheli' else 'straightforward')
for lang,words in [('Malvi','uppar|uparā|upəre|upar|upər'),('Nimadi','uppar|upero|upar|upərā'),('Bagheli','upəṛe|upəṛ|upər')]:
 b.add(lang,'above',words,'2333','CDIAL 2333 reconstructs *uppari with emphatic consonant lengthening of upari, and explicitly gives Punjabi uppar, Hindi ūpar, Old Marwari upari/ūpara and Gujarati upar. The adverbial meaning selects 2333 rather than *uppara ‘upper’; '+('Bagheli retroflex ṛ and final -e require local phonological/adverbial review.' if lang=='Bagheli' else 'local short vowels and final -o/-ā/-e are qualified regional/adverbial variants.'),tier='qualified')
for lang,words in [('Malvi','nicːe|nico|nice|nic.e|nitse|nica|nise'),('Nimadi','nice|nicə'),('Bagheli','nice')]:
 b.add(lang,'below',words,'7540','CDIAL 7540 includes nīcā ‘below’ and explicitly explains the widespread -cc- forms by influence of opposite ucca; it gives Old Marwari nīcaï ‘below’, Oriya nice and Gujarati nīcε adverbs. '+('Malvi c/ts/s and gemination spellings are retained as qualified local variants; nic.e is preserved exactly as transcribed.' if lang=='Malvi' else 'The survey adverb matches this low/below family; vowel length and final vowel variation are retained.'),tier='qualified' if lang=='Malvi' else 'straightforward')
for lang,words in [('Nimadi','nicho|nichā'),('Bagheli','nich|niche')]:
 b.add(lang,'below',words,'7540','CDIAL 7540 connects nīca ‘low’ and the nīce-type adverbs ‘below’ through a -cc- stem influenced by opposite ucca. These ch spellings are a qualified family proposal: aspiration is not established by the primary article for these survey lects and must not be silently normalized away.',tier='qualified')
b.add('Malvi','left','ḍābo|ḍaba','5539-3','This is specifically CDIAL 5539.3 *ḍābba: Old Gujarati ḍābaü, Gujarati ḍābũ/ḍābhũ and the addendum’s Kacchi ḍābo all mean ‘left’. Turner places the broader family under a non-Aryan/Dravidian-origin hypothesis; the proposal identifies this b-branch, without claiming a demonstrated immediate Dravidian donor.',tier='qualified',locator='5539.3')
for lang,words in [('Malvi','ḍavo|ḍāvo|ḍavā'),('Nimadi','ḍavo|ḍāõ')]:
 b.add(lang,'left',words,'5539-2','This is specifically CDIAL 5539.2 *ḍāva: Prakrit ḍāva ‘left hand’, Sindhi ḍāo ‘left’, Hindi ḍāwā and Marathi ḍāvā. The v-bearing forms fit this section rather than *ḍābba; local vowel length/nasalization and Turner’s non-Aryan-origin hypothesis remain qualified.',tier='qualified',locator='5539.2')
for lang,words in [('Malvi','unːo|unːā|unːa|unːu'),('Nimadi','uno')]:
 b.add(lang,'hot',words,'2389','CDIAL 2389 uṣṇa explicitly gives Pali/Prakrit uṇha, Gujarati ūnũ/hunũ and Marathi ūnh/ūn ‘hot’. Loss of the medial aspiration and the n-type western forms support this family; '+('Malvi’s short vowel with geminate n and -o/-ā/-a/-u endings are retained for review.' if lang=='Malvi' else 'Nimadi uno differs in recorded vowel length from Gujarati ūnũ and is qualified accordingly.'),tier='qualified')
b.add('Malvi','hammer','ghaṇ','4423','CDIAL 4423 ghaná ‘club, hammer’ explicitly gives Prakrit ghaṇa ‘hammer’ and Punjabi, Gujarati and Marathi ghaṇ ‘sledgehammer’. The retained initial aspiration and retroflex nasal match these western comparanda; the survey’s broader hammer meaning is compatible.')
b.add('Malvi','cloth','latta|letto|letta','10930','CDIAL 10930.1 *latta lists Awan lattā and Kumaoni lātā/lattā/latā ‘clothes’, alongside Hindi lattā ‘tattered cloth’ and Gujarati lattũ ‘rag’. The full article supplies the cloth sense beyond the broad head gloss ‘defective’; e-vowels and the expressive family’s deep origin remain qualified.',tier='qualified',locator='10930.1')
b.add('Malvi','cloth','latəra|lattra','10930-2','CDIAL 10930.2 *lattara is a distinct extended branch, with Hindi latrā ‘tattered, torn’ and Bihari latrī ‘old shoes’, beside section 1’s cloth/rag nouns. The r-bearing survey cloth forms are assigned provisionally to that extension, with nominal meaning and local vowels still requiring review; they are not collapsed into bare *latta.',tier='qualified',locator='10930.2')
for lang,words in [('Malvi','jamna|jimṇa|jimna|jivṇa|jamṇo|jivṇā'),('Nimadi','jauṇu|jaũṇo|jevṇu|jaunu|jauṇo')]:
 b.add(lang,'right',words,'5268','CDIAL 5268 jēmana ‘eating’ explicitly includes Prakrit jēmaṇaya ‘right (eating) hand’ and Old Gujarati jimaṇaüṁ ‘to the righthand side’, alongside Old Marwari jīmaṇa. This supplies the semantic bridge; m/v variation and '+('Malvi a/i vowels' if lang=='Malvi' else 'Nimadi vowel coalescence and loss of intervocalic v')+' are qualified regional developments, not evidence of a specific donor language.',tier='qualified')
for lang,words in [('Malvi','uñco|uco|ucyo|uncyā'),('Bagheli','unce|ūce')]:
 b.add(lang,'above',words,'1634','CDIAL 1634 includes uccā/uccaiḥ ‘above’, Old Marwari uco, Hindi ū̃c/ū̃cā and Gujarati ū̃cũ; adverbial use of the high adjective fits the elicitation. Turner explicitly doubts deriving nasal forms directly from udañc, so nasalization and local endings are qualified rather than assigned a separate unsupported parent.',tier='qualified')
for lang,words in [('Nimadi','ucho'),('Bagheli','ūch|ūcha')]:
 b.add(lang,'above',words,'1634','CDIAL 1634 ucca supplies the high/above family and discusses aspirated Western Pahari forms in its addendum as analogical influence from words of upward movement. The local ch spellings are a qualified comparison only: that Western Pahari explanation is not established for these survey lects, and neither a donor nor a regular local aspiration rule is asserted.',tier='qualified')
b.save()
