from research_helpers import Batch
b=Batch(9);a=b.add
# Every listed response was inspected: no auxiliary or negator is included in these selections.
a('Malvi','eat!, he ate','khao|khā|khāo','3865','CDIAL 3865.1 gives Prakrit khāaï/khāi, Hindi khānā, Marwari khābo and Gujarati khāvũ. These selected khā-/khā-o imperatives contain the eating stem and an ordinary imperative ending; compound completives are excluded.',locator='3865.1')
a('Nimadi','eat!, he ate','khā','3865','The bare imperative khā matches the regional eating stem in CDIAL 3865.1 (Hindi khānā, Marwari khābo). Paired responses with auxiliaries are not included.',locator='3865.1')
a('Malvi','eat!, he ate','khāiyā','3865-2','CDIAL 3865.2 khādita compares Prakrit khāyita and Hindi khāyā ‘ate’. This selected past form belongs with the participial branch; it is not grouped under the present khādati.')
a('Malvi','eat!, he ate','jimo|jimiya','5267-2','CDIAL 5267.2 compares Prakrit/Old Gujarati jimaï ‘eats’, while branch 3 gives Prakrit jimmaï and Old Marwari jīmaï. The survey’s short i favors branch 2, but vowel transcription does not exclude *jimyati/*jimmati; retain branch 3 as an alternative.',tier='qualified')
a('Malvi','bite!, he bit','kāṭaṇo|kāṭyo|kaṭā|kaṭyo|kāṭ','2854','CDIAL 2854 gives Prakrit kaṭṭaï, Hindi kāṭnā and Gujarati kāṭvũ ‘cut’. The survey’s bite sense is compatible with cutting by the teeth, but this semantic extension is not itself documented in the checked article; keep the proposal qualified.',tier='qualified')
a('Bagheli','bite!, he bit','kaṭ|kaṭa|kaṭā|kaṭi|kaṭis|kaṭisi','2854','The stem compares Hindi kāṭnā and Awadhi kāṭab under CDIAL 2854 ‘cut’; the -is/-isi past endings are inflectional candidates. Both the cut-to-bite extension and the local tense morphology require review; auxiliary-bearing kaṭ-lih-/kaṭ-ḍ- forms are excluded.',tier='qualified')
a('Malvi','drink!, he drank','pio|piṇo|piõ','8209','CDIAL 8209 compares Prakrit pi(v)aï, Hindi pīnā, Gujarati pīvũ and Marathi piṇẽ. These selected imperative/infinitive forms continue the drinking stem; pī-l- completives and ambiguous bare past forms are excluded.')
a('Malvi','sleep!, he slept','sov|soyā','13902','CDIAL 13902 compares Prakrit sō(v)aï, Hindi sonā, Awadhi sōwab and Old Marwari soaï. The v/y forms continue this present-stem family with ordinary inflection; the inherited sūt-/hūt- participle is a different branch.')
a('Malvi','lie down!, he lay down','soya','13902','CDIAL 13902 explicitly gives Bengali soyā ‘sleep, lie down’ and Assamese xoiba ‘lie down’, alongside the central sō- family. The selected simple soya has the same compatible posture sense; auxiliary-bearing responses are excluded.')
for l,w in [('Malvi','beṭyo|baṭho|baiṭo|beṭho|beṭha|beṭṭiya|beṭhya|bēṭ'),('Nimadi','baṭiyoj'),('Bagheli','bet|beyth|beythe|beytho|bheythe')]:
 a(l,'sit down!, he sat down',w,'14327','CDIAL 2245 explains that ṭ/ṭh sitting stems were remade from upaviṣṭa, comparing Hindi baiṭhā/baiṭhnā and Gujarati bεṭho; addendum 14327 supplies the explicit upaviṣṭa node. The family is qualified because Turner notes contamination and phonetic difficulties, and some survey forms have reduced aspiration or added particles.',tier='qualified',locator='2245, upaviṣṭa, 14327')
a('Malvi','give!, he gave','de','6141','CDIAL 6141 derives regional de- from Middle Indo-Aryan dēti/dēi, remodeled with imperative dēhi and the ‘take’ paradigm. The bare imperative belongs here; diyā and doubled de-de are excluded from this proposal.')
for l,w in [('Malvi','māriyo|mara'),('Bagheli','maris|marisi|maṛa|maṛisi')]:
 a(l,"don't kill!, he killed",w,'10066','CDIAL 10066 compares Prakrit māraï, Hindi mārnā, Old Marwari māraï and Awadhi mārab ‘strike, kill’. Only the simple killing stem and candidate inflections are included; negated and auxiliary-bearing responses are excluded.',tier='qualified')
a('Malvi','fly!, it flew','uḍo|uḍi|uḍ|uḍyo|uḍiyo|uḍə|uḍa','1697-2','CDIAL 1697.2 compares Prakrit uḍḍēi, Old Marwari ūḍaï and Gujarati uḍvũ. Its addenda explicitly allow *uddayati as an alternative for potentially all these forms; this is a qualified family proposal, not proof of a uniquely retroflex Old Indo-Aryan source.',tier='qualified')
a('Bagheli','fly!, it flew','uḍeṭa','1697-2','Compare Old Marwari ūḍaï and Awadhi uṛab in CDIAL 1697.2. The source’s final -eṭa appears inflectional but needs local analysis, and Turner explicitly retains *uddayati as an alternative origin of the fly family.',tier='qualified')
for l,w in [('Malvi','calo|calā|cala|cal|caliyo|cale|calyā|calya'),('Nimadi','calre, calyo|cal, calyo|calo, cālā|calo, tsalyo'),('Bagheli','cel|cela|celeṭa|cele|celi|celna|celo|celu|cal')]:
 a(l,'walk!, he walked',w,'4715','CDIAL 4715 gives Prakrit calaï, Hindi calnā and Old Marwari calaï; contrast long-vowel cāl- under 4721. '+('Each selected pair has two inflections of this same stem (cal-re includes a vocative particle); no gayo or other auxiliary is present. ' if l=='Nimadi' else '')+'The survey’s vowel lengths and eastern e-vowels may not uniquely distinguish calati from calyati, and Turner documents contact spread into eastern languages.',tier='qualified')
a('Malvi','walk!, he walked','cāl|cālo','4721','CDIAL 4721 *calyati gives Prakrit callaï, Marwari cālṇo and Gujarati cālvũ. The explicitly long ā favors this geminate-derived branch over short-vowel calati; the selected forms contain no auxiliary.')
for l,w in [('Malvi','ḍoḍo|doḍ|doḍiyo|douḍ|dauḍ|doḍiya|dodə|doḍyo'),('Nimadi','dauḍo|dāuḍ, dāuḍiyo|davaḍ, davḍyo'),('Bagheli','ḍeuḍ|ḍeuḍa|ḍeuḍe|ḍeuṛ|ḍeuṛa|ḍeurə|ḍeuro|ḍeur|ḍeurəṭ')]:
 a(l,'run!, he ran',w,'6624-2','CDIAL 6624’s -ḍ- extension compares Hindi dauṛnā, Marwari doṛṇo, Gujarati doṛvũ and Marathi davaḍṇẽ/dauḍṇẽ. The specific extension node accounts for the medial retroflex; selected paired responses are simple inflections of that stem, while source vowels, initial ḍ and any final tense endings remain subject to local review.',tier='qualified',locator='6624, -ḍ- extension')
for l,w in [('Malvi','bhago|bhagiyo|bhagyo'),('Bagheli','bhagæ')]:
 a(l,'run!, he ran',w,'9361-2','CDIAL 9361.2 traces g-bearing flee/run verbs through bhagna and Prakrit bhagga, comparing Hindi bhāgnā, Awadhi bhāgab and Old Marwari bhāgaï. Turner discusses a competing ‘flee’ root but considers coalescence with ‘break’ complete; do not assign these to the j-bearing present branch.',tier='qualified')
for l,w in [('Malvi','jāo|jāvo|jā|jau|jāv|jao'),('Nimadi','jā'),('Bagheli','ja|jao|jau|jav')]:
 a(l,'go!, he went',w,'10452','CDIAL 10452 gives Prakrit jāi, Hindi jānā, Old Marwari jāvaï (imperative jā) and Gujarati javũ. These selected simple imperative forms belong to yāti; suppletive gayo/gya past forms are excluded.')
for l,w in [('Malvi','av|āvo|ā|avo|āvjo'),('Bagheli','a|āba|ao|av|aua|auæ|auə|auo')]:
 a(l,'come!, he came',w,'1200','CDIAL 1200 specifically compares Prakrit āvaï ‘comes’, Hindi ānā with stem āw-, Old Marwari āvaï and Gujarati āvvũ under āpayati. The selected come-imperatives belong here, while āyo past forms and ā-ja compounds require separate analysis.',tier='qualified' if l=='Bagheli' else 'straightforward')
for l,w in [('Malvi','bol|boliyā|boliyo|bolo|boliya|bolā|bolyo'),('Nimadi','bol, bolyo|boḷə, boḷyo|bol, boliyo|bolṇu'),('Bagheli','bola|bol|boḷu|bole|bolə|bolo')]:
 a(l,'speak!, he spoke',w,'9321','CDIAL 9321 gives Prakrit bollaï, Hindi bolnā, Old Marwari bolaï and Gujarati bolvũ. Only simple inflections of bol- are grouped (both members in selected Nimadi pairs); the remote origin of *bōll is debated in the article and is not asserted here.')
for l,w in [('Malvi','suṇo|suṇ|sun|sunyo|suṇiyo|suṇiya|suno|sunā'),('Nimadi','suṇo|suṇə, suṇyo|suṇ, suṇyo|suṇ, suṇa|sun, sunyo'),('Bagheli','sun|suna|sunen|sunyo|sunēu|sunin')]:
 a(l,'listen!, he heard',w,'12598','CDIAL 12598 gives Pali suṇāti, Prakrit suṇaï, Hindi sunnā, Marwari suṇṇo and Awadhi sunab. Selected forms and pairs contain the same listening stem with ordinary inflections; sun-li- and auxiliary-bearing responses are excluded.',tier='qualified' if l=='Bagheli' else 'straightforward')
a('Malvi','listen!, he heard','huṇo|huṇ|huṇi|huṇiyo','12598','The medial ṇ and inflections compare Marwari suṇṇo in CDIAL 12598. Initial h is a plausible local s/ś-to-h development, consistent with other Malvi candidates, but requires independent dialectal evidence.',tier='qualified')
for l,w in [('Malvi','dekho|dekhiyo|dekh|dekhyo|dekhya'),('Nimadi','dekh, dekhyo|deko,deki'),('Bagheli','ḍekhen|ḍekha|ḍekhin|ḍekhis|ḍekhyo|ḍekla|ḍekəu|ḍikhen|ḍikhin')]:
 a(l,'look!, he saw',w,'6507-2','CDIAL 6507.2 specifically gives Aśokan dekhati, Prakrit dekkhaï and Hindi/Marwari dekh-; it also explains some i-vowel forms through later change or participial influence. Selected pairs contain two forms of the seeing stem; deaspiration and Bagheli ḍ/i need local review, and historical contact spread is explicitly documented.',tier='qualified')
for pp in b.proposals.values():
 for x in pp:
  if x['parentId']=='5267-2':x['alternatives']=[{'parentId':'5267-3','reason':'Short/long i and jim-/jimm- history unresolved.'}]
  if x['parentId']=='1697-2':x['alternatives']=[{'parentForm':'*uddayati','reason':'Explicit alternative in CDIAL addenda; not installed as a new node.'}]
b.save()
