from research_helpers import Batch
b=Batch(10);a=b.add
def family(l,meaning,words,parent,evidence,tier='straightforward',senses=None,locator=None):
 allowed=[g for g in dict.fromkeys(r['Gloss'] for r in b.inv[l]) if set(g.split('; ')) <= set(senses or [meaning])]
 b.add(l,meaning,words,parent,evidence,tier,locator=locator,source_glosses=allowed)
for l,w in [('Malvi','kuṇ|kuṇə|koṇ'),('Nimadi','kuṇə|kuṇ|kunə|koṇə'),('Bagheli','keun|kon')]:
 a(l,'who?',w,'2575','CDIAL 2575 kaḥ punar gives Apabhramsha kavaṇa, Old Marwari kõṇa/kuṇa, Gujarati kɔṇ, Maithili kon and Hindi kaun. The nasal-ending interrogatives have direct regional comparanda.',tier='qualified' if l=='Bagheli' else 'straightforward')
for l,w in [('Malvi','kay|kai|kãi|kāi'),('Nimadi','kāy|kāi')]:
 a(l,'what?',w,'3196-2','CDIAL 3196 explicitly replaces kīdṛk by *kādṛk, comparing Old Gujarati kaya ‘what?’ and Marathi kāy. This fits the y/diphthong forms; the separate kīdṛśa ‘what kind?’ formation is not used.',tier='qualified' if l=='Malvi' else 'straightforward',locator='3196, *kādṛk')
for l,w in [('Malvi','kitra|katrā|kitrā|katro|katara|katra|ketra'),('Nimadi','kitra|ketro|ketrā|kitrā|katra')]:
 a(l,'how many?',w,'3167','CDIAL 3167’s explicit -r- extension compares Lahnda kitrā and Old Marwari kītarāka; addenda give ketrɔ/ketri. This licenses the extended stem, with regional i/e/a and gender-ending variation.',tier='qualified',locator='3167, -r- extension')
for l,w in [('Malvi','kite|kitːi|kitːa|kitːo|kitā'),('Nimadi','kettā')]:
 a(l,'how many?',w,'3167','CDIAL 3167 compares Prakrit kittiya, Hindi kittā/kitā and the addenda’s ketti ‘how much, how many’. The geminate or simplified t forms fit the base *kiyatta family.')
a('Malvi','how many?','kitna','3167','CDIAL 3167 explicitly lists Hindi kitnā and related -n- extended forms. The family is clear, but Hindi contact versus independent local inheritance of this extension remains unresolved.',tier='qualified',locator='3167, -n- extension')
a('Bagheli','how many?','ketena|keṭena|keṭna|kiṭena|kiṭina|ketna','3167','CDIAL 3167 lists the -n- extension Hindi kitnā and addenda ketṇo. The Bagheli forms fit this family provisionally; internal vowel variation and transcribed ṭ require local confirmation.',tier='qualified',locator='3167, -n- extension')
for l,w in [('Malvi','kaiso|kaso|keso|kaisā|kaśo|kasā|kasi|kāśā|kaśā|kasiyo'),('Nimadi','kaso|kasa|kāso|kasi'),('Bagheli','keysa|keysen|keyse')]:
 a(l,'what kind?',w,'3197','CDIAL 3197 derives kaisa-type forms by analogy with yādṛśa/tādṛśa, giving Apabhramsha kaïsa, Awadhi kaisa and Hindi kaisā; it also compares Marathi kasā. The family is qualified because analogy, vowel variation and possible Hindi contact prevent a uniquely regular inherited derivation.',tier='qualified')
for l,w in [('Malvi','pura|purā|puro'),('Nimadi','puro|purā'),('Bagheli','pur|pura|puri|pure')]:
 family(l,'whole/all',w,'8330','CDIAL 8330 compares Hindi pūrā, Old Marwari puraü, Gujarati pūrũ and Marathi purā ‘full, complete’; Shina pūrṷ also means ‘all’. The selected whole/all meanings and ordinary gender forms are compatible.',senses=['whole','all'])
for l,w in [('Malvi','gheṇo|ghaṇu|ghano'),('Nimadi','ghaṇ̃u|ghaṇu|ghano|ghaṇā|ghaṇa')]:
 a(l,'many',w,'4424','CDIAL 4424 compares Sindhi ghaṇo ‘much, many’, Old Gujarati ghaṇauṁ ‘much’, and Marwari ghaṇo ‘big’. The dense-to-abundant sense development is explicitly attested.',locator='4424.1')
a('Malvi','many','gaṇo|gaṇoi|gaṇā','4424','Compare the abundant/many sense of ghaṇo in CDIAL 4424.1. The deaspirated g- and extra ending in gaṇoi require local confirmation, so this is a qualified connection rather than automatic spelling normalization.',tier='qualified',locator='4424.1')
for l,w in [('Malvi','bhot|bahot|bahut|bot'),('Nimadi','bəhut|bhot'),('Bagheli','behuṭ')]:
 a(l,'many',w,'9190','CDIAL 9190 compares Prakrit bahutta ‘much’, Old Marwari bahuta/bahota/bhota and Gujarati bɔt. Turner notes adjective formation with probable influence from prabhūta; the proposed bahutva family preserves that qualification.',tier='qualified')
for l,w in [('Malvi','sab|śob|səb|śab|sāb'),('Nimadi','sabai|sabay|sab|sabhi'),('Bagheli','seb|sebey')]:
 a(l,'all',w,'13276','CDIAL 13276 compares Prakrit savva, Hindi/Awadhi sab and Bhojpuri sabh, but its addenda identify Old Marwari saba as a Hindi loan. The family is well supported; inheritance versus regional contact and emphatic endings remain unresolved.',tier='qualified')
a('Malvi','all','hab','13276','CDIAL 13276 explicitly discusses h for s in pronominal words and gives Lahnda habba/habh beside sabbho. Malvi hab is a plausible family member, but those distant comparanda do not establish the local transmission route.',tier='qualified')
a('Malvi','I (1 person singular)','hũ','992','CDIAL 992 aham gives Apabhramsha haü̃, Old Marwari hũ/hu and Gujarati hũ. This directly supports the h-initial first-person nominative.')
a('Nimadi','I (1st person singular)','haũ|hāũ|hā̃u','992','CDIAL 992 gives Apabhramsha haü̃, Braj haũ and Old Marwari hũ; the retained diphthong and nasalization support the aham nominative family.')
a('Malvi','I (1 person singular)','mū|mẽ','9691','CDIAL 9691 explains replacement of aham by oblique ma- forms, comparing Old Marwari mẽ and several mũ forms. The source’s mū may omit nasalization; retain this spelling and qualify the exact development.',tier='qualified')
a('Bagheli','I (1st sg)','mey|may|me','9691','CDIAL 9691 gives Prakrit instrumental maē, Apabhramsha maï̃, Old Awadhi maïṁ and Hindi maĩ used as nominatives. The Bagheli mV/y forms fit this oblique-to-nominative replacement; source nasalization remains uncertain.',tier='qualified')
family('Malvi','you (singular informal)','tu','5889','CDIAL 5889.1 gives Prakrit tuṁ and Hindi/Old Marwari tū. The bare informal singular tu fits this nominative branch.',senses=['you (2 person singular, informal)'],locator='5889.1')
family('Nimadi','you (singular informal/formal)','tu','5889','CDIAL 5889.1 compares Prakrit tuṁ, Hindi tū and Marathi tũ. Both source politeness labels attach to the same form; politeness variation does not change the historical singular stem.',senses=['you (2nd person singular, informal)','you (2nd person singular, formal)'],locator='5889.1')
a('Bagheli','you (2nd sg, informal)','ṭu|ṭū|ṭūy','5889','CDIAL 5889.1 compares Hindi tū and Prakrit tuṁ. The source’s retroflex ṭ and final y need local phonological confirmation; they are not silently respelled as Hindi.',tier='qualified',locator='5889.1')
family('Malvi','you (formal singular/plural)','tam|tami|tum|tamu','10511','CDIAL 10511 explains t-initial forms from tumhē, remodeled from yuṣmad with influence from tvam; compare Hindi tum and Gujarati tamε. Polite singular and plural uses are compatible, but local vowel/ending variation remains qualified.',tier='qualified',senses=['you (2 person singular,formal)','you (2 person plural)'])
family('Nimadi','you (formal singular/plural)','tum|tam|tām','10511','CDIAL 10511 gives Prakrit tumhē, Hindi/Awadhi tum and Gujarati tamε. The source’s formal singular use is an ordinary extension of the plural form; the a/u variants retain a qualified local analysis.',tier='qualified',senses=['you (2nd person singular, formal)','you (2nd person plural)'])
family('Bagheli','you (singular/plural)','ṭum','10511','CDIAL 10511 gives Hindi/Awadhi tum from the remodeled plural tumhē. The source uses this form across number/politeness categories; its initial retroflex stop remains a transcription/correspondence question.',tier='qualified',senses=['you (2nd sg, informal)','you (2nd sg, formal)','you (2nd pl)'])
family('Malvi','we (inclusive/exclusive)','ham|hami|hamu','986','CDIAL 986 explains the plural from Middle Indo-Aryan amhē and related oblique forms, explicitly comparing Hindi, Awadhi and Bihari ham. Inclusive/exclusive labels denote compatible uses; the final vowels are local pronominal extensions.',tier='qualified',senses=['we (1 person plural, inclusive)','we (1 person plural, exclusive)'])
family('Nimadi','we (inclusive/exclusive)','ham|hām','986','CDIAL 986 explicitly gives Hindi/Awadhi/Bhojpuri ham under asmad and Middle Indo-Aryan amhē. The same form serves both elicited clusivity categories in this survey.',senses=['we (1st person plural, inclusive)','we (1st person plural, exclusive)'])
b.save()
