from research_helpers import Batch
b=Batch(32)
for lang,words in [('Malvi','dāyā|daina|dāyo|dai'),('Nimadi','dāyo|dahino'),('Bagheli','ḍehina|ḍehine|ḍeyna|ḍahin|ḍahina|ḍahine|ḍuhina|ḍay|ḍayə|ḍāyə|ḍāye')]:
 b.add(lang,'right',words,'6251','CDIAL 6251 dākṣiṇa specifically gives Prakrit dāhiṇa/ḍāhiṇa ‘right’, Old Awadhi dā̆hina, Hindi dā̆hinā and Braj dahino, plus Hindi dā̃yā explained by crossing with vāma ‘left’. The h-bearing and contracted y-forms therefore belong to this long-vowel derivative rather than automatically to bare dakṣiṇa; local vowels, endings and loss of nasalization are qualified. '+('Prakrit already supplies initial ḍ, although Bagheli e/u vowels still need local review.' if lang=='Bagheli' else 'No specific contact donor is established.'),tier='qualified')
for lang,words in [('Malvi','bā̃yā|bayo|bay'),('Nimadi','bāyo'),('Bagheli','bayə|bayē|bāyə|bāyā|bāye')]:
 b.add(lang,'left',words,'11533','CDIAL 11533 vāma gives Kumaoni bāyõ, Old Awadhi bāeṁ ‘on the left’, Hindi bāyā̃ and Oriya bāyā̃ ‘pertaining to the left’. These y-bearing forms fit loss of intervocalic m with variable nasalization and v→b; unmarked nasalization and local final vowels remain qualified. Retained-m bama/bāmā and the h-bearing behiya are not silently grouped here.',tier='qualified')
for lang,words in [('Malvi','uḷṭā|uḷṭo'),('Nimadi','uḷṭa|ulṭo')]:
 b.add(lang,'left',words,'2368-2','CDIAL 2368.2 *ullaṭyate specifically includes Prakrit ullaṭṭa ‘overturned’, Old Marwari ulaṭo ‘reversed’, and the addendum’s Kotgarhi ulṭɔ ‘left, reverse’. The adjective and its left-hand semantic extension select section 2 rather than section 1’s ulaṛ-type verb; retroflex ḷ and regional vowel endings remain qualified.',tier='qualified',locator='2368.2')
for lang,words in [('Malvi','heṭṭā'),('Nimadi','heṭa|heṭā')]:
 b.add(lang,'below',words,'248-2','CDIAL 248.2 *adhiṣṭāt (remodelled after upariṣṭāt) gives Pali heṭṭhā, Prakrit heṭṭha/hiṭṭha ‘below’, Bhojpuri heṭhā̃, Old Awadhi heṭha, Gujarati heṭhe and Marathi heṭ. The survey’s loss of aspiration and varying gemination fit a qualified regional continuation of this specific second branch, not undifferentiated adhastāt.',tier='qualified',locator='248.2')
for lang,words in [('Malvi','sido|sidā'),('Nimadi','sito|sido')]:
 b.add(lang,'right',words,'13401','CDIAL 13401.1 siddha lists Sindhi sidho, Hindi sīdhā and Gujarati sīdhũ in the straight/upright family; Platts s.v. sīdhā explicitly supplies the right-hand sense and its Prakrit siddhao formation. Loss of aspiration and '+('Nimadi t/d variation' if lang=='Nimadi' else 'local final vowels')+' remain qualified; sudo/huda may involve a different clean/straight family and are excluded.',tier='qualified',citation='CDIAL[13401.1];Platts[s.v. sīdhā]',source_url='https://www.rekhta.org/urdudictionary?keyword=siidhaa')
b.save()
