from research_helpers import Batch,P
from shutil import copyfile
b=Batch(34)
for lang,words in [('Malvi','carbi|sarbi|carəbi'),('Nimadi','carbi|carəbi|cārbi'),('Bagheli','cerbi|cərbi')]:
 b.add(lang,'fat',words,'f_cdzupphnjmodm','Borrowing proposed from attested Hindi carbi ‘fat’ (Kannauji survey p. 75, Hindi comparison lects), ultimately Persian ćarbī. Platts explicitly defines ćarbī as animal fat/grease/suet; local epenthesis and vowel variation'+(' and c→s in sarbi' if lang=='Malvi' else '')+' remain qualified, and the selected Hindi record represents the donor lexeme rather than proof of a particular donor village.',tier='qualified',kind='borrowed',citation='kannauji[p. 75];Platts[s.v. ćarbī]',source_url='https://www.rekhta.org/urdudictionary?keyword=charbii')
for lang,words in [('Malvi','makān'),('Nimadi','məkān'),('Bagheli','mekan|mekhan|maka')]:
 b.add(lang,'house',words,'f_bk76lqk32ood6','Borrowing proposed from the existing Hindi makān ‘house’ in Grierson’s comparative vocabulary (pp. 102–103, WESTERNHINDIHINDOSTANI-51_house-1); Platts confirms makān ‘dwelling/house’ and its Arabic origin. '+('Bagheli e-vowels, aspiration in mekhan and final-n loss in maka remain qualified. ' if lang=='Bagheli' else 'Local vowel realization is retained. ')+'The Hindi donor is currently unlinked: acceptance requires resolving its ancestry/status first, without creating a new donor or bypassing Hindi to Arabic.',tier='qualified',kind='borrowed',citation='grierson-lsi1928[p. 102-103, WESTERNHINDIHINDOSTANI-51_house-1];Platts[s.v. makān]',source_url='https://www.rekhta.org/urdudictionary?keyword=makaan')
 b.proposals[lang][-1]['acceptanceDependency']={'type':'unlinked-donor','parentId':'f_bk76lqk32ood6'}
b.add('Malvi','meat','gos|gōs','f_qbahea6yfb6qm','Borrowing proposed from attested Hindi gost ‘meat (raw)’ (Kannauji survey p. 75), ultimately Persian gōšt; Platts independently supplies the broader meat/flesh sense. Final-t loss and s for š are qualified regional adaptation; the immediate Hindi donor is preserved and the survey does not specify raw versus cooked meat.',tier='qualified',kind='borrowed',citation='kannauji[p. 75];Platts[s.v. gosht]',source_url='https://www.rekhta.org/urdudictionary?keyword=gosht')
copyfile('/tmp/central-murghi.png',P/'platts-murghi.png')
for lang,words in [('Malvi','murgi'),('Nimadi','murəgi|murgi'),('Bagheli','murgi')]:
 b.add(lang,'chicken',words,'f_5azv73u3n6upa','Borrowing proposed from attested Hindi murgi ‘chicken’ (Kannauji survey p. 75, Rohili comparison record), not directly from Persian murġ. The full Platts murġī entry, visually checked in the cached DSAL edition (PDF page 2075), labels it Hindi ‘hen’ and derives the feminine from murġ; hen→generic chicken and '+('Nimadi epenthesis' if lang=='Nimadi' else 'vowel length')+' remain qualified, and Rohili is an attestation proxy rather than an identified donor village.',tier='qualified',kind='borrowed',citation='kannauji[p. 75];Platts[s.v. murġī]',source_url=str(P/'platts-murghi.png'))
b.save()
