import json,datetime
from pathlib import Path
p=Path(__file__).resolve().parent;h=json.loads((p/'holds.json').read_text());d=json.loads((p/'dispositions.json').read_text())
groups=[('Malvi','father','pitā','CDIAL 8179 supplies Sanskrit pitā and its piu-type reflexes. The retained t suggests a learned/conservative form, but immediate transmission remains unresolved; Hindi search found pitā kā paternal, not a standalone father donor.'),('Bagheli','father','piṭa','CDIAL 8179 pitṛ is the semantic family, but retained retroflex ṭ and immediate learned/contact transmission need evidence; no standalone Hindi father donor was found.'),('Malvi','wife','patni','CDIAL 7742 patnī wife has Prakrit pattī. Retained tn suggests a learned form; immediate donor remains unresolved. The Hindi search result paṭnī ferryman is unrelated and must not be used.'),('Bagheli','wife','peṭni','CDIAL 7742 patnī is the likely learned family, but retroflex ṭ, e-vocalism and immediate transmission remain unresolved; do not use Hindi paṭnī ferryman.'),('Nimadi','woman','bay|bāi','CDIAL 9198.2 bāī explicitly supplies mother but does not establish the survey woman sense or separate it from sister-derived bāi (homepage Nihali comparisons under bhaginī). Further primary evidence is needed before selecting a parent.'),('Nimadi','wife','bairu|bairo|bāiru','Full CDIAL 9471 bhāryā/*bhāriyā gives Prakrit bhajjā/bhāriā and Sinhala biriya, but does not establish this western bāiru family or its deaspiration/metathesis. Homepage Gujarati/Marwari comparanda are unlinked; Platts bairī enemy/falcon are wrong homonyms.'),('Malvi','wife','bhera|beirā','The bhāryā/*bhāriyā family is a possible lead, but full CDIAL 9471 does not establish these local forms or distinguish the bāī-related alternative. More primary regional evidence is required.')]
n=0
for l,g,ws,reason in groups:
 for r in d[l]:
  if r['status']=='unexamined' and r['gloss']==g and r['form'] in ws.split('|'):
   h[r['id']]={'survey':l,'form':r['form'],'gloss':g,'reason':reason,'researchStatus':'investigated-unresolved','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat()};n+=1
(p/'holds.json').write_text(json.dumps(h,ensure_ascii=False,indent=2));print('New researched holds',n)
