import csv,json,re
from pathlib import Path
P=Path(__file__).resolve().parent
exec((P/'sixth_prepare.py').read_text().split('qs=[]')[0])
qs=[]
def add(parent,gloss,words,citation,ev):qs.append(dict(parent=parent,gloss=gloss.split('|'),words=words.split('|'),citation=citation,evidence=ev))
add('f_a3zgar2k27pzm','cauliflower','phulgobhi|phulgobi|phul gobi|phulkobi|fulgobi|ɸulgobi|ɸul-kobi|phul gubi|ɸul gobi|pul kobi|pul gubi|phulkopi|fulgopi|phul kobi|phulghobi|phul gopi|phulgopi|ɸulgobhi|phoolgobhi','centralbank-saral-kannada[PDF p. 11, vegetables, item 4];platts1884[s.v. kobī]','The primary Hindi vegetable table, visually checked at PDF page 11 item 4, gives फूलगोबी “cauliflower”. Platts p. 858 independently lists phūl-kobī. The survey forms preserve the entire flower-plus-cabbage compound, with pʰ/f/ɸ and g/k or b/p regional adaptations; their precise Indo-Aryan transmission remains provisional.')
add('f_ody2xkuwe2bqg','cabbage','bandgobi|bandigobi|band gobi|bandakobi|bandgobhi|bandakopi|bandhagobhi|band gopi|bantgobhi|bandha kobi|banda gobi|bandagobi|bandhakobi|badgobi|ban gopi','cstt-agriculture-eng-hin-dogri[s.v. cabbage]','The existing donor audit transcribes the CSTT Hindi cabbage cell as बंदगोभी, supporting the whole band-gobhi compound. These survey forms preserve both members, allowing cluster simplification and g/k, b/p variation. The original donor-source fact is cached in the 20260911 audit; a fresh PDF fetch timed out. This provisional Hindi-family loan does not reconstruct the compound in Sanskrit.')
add('f_jngmzar4rfvqg','cabbage|cauliflower','gobi|gopi|gupi|kobi|kobhi|gobhi|gobbi|ghobi|gophi','CDIAL[4270];platts1884[s.v. gobhī, gobī, kobī]','CDIAL 4270 explicitly groups Hindi gobhī/gobī/kobhī/kopī and Nepali gobhi/gobi/kobi/kopi for cabbage, with Awadhi cauliflower. Platts independently attests gobhī/gobī and cross-refers kobī. Linking provisionally to the existing Hindi gobī attestation identifies the regional vegetable-word family while leaving competing ultimate plant-name derivations unresolved.')
add('f_ioja36d77utxa','tomato','ṭamaṭar|tamatar|tamaṭar|ṭimaṭar|ṭemaṭer|ṭamaṭer|ṭamaṭaṛ|ṭamaṭari|ṭamaṭeria|ṭamaṭariyo','kannauji[p. 74];centralbank-saral-kannada[PDF p. 11, vegetables, item 3]','The existing Rohili Hindi ṭamaṭar tomato attestation is independently supported by the visually checked primary Hindi table, PDF page 11 item 3 टमाटर. The selected r-ending survey forms preserve this whole regional loan word, with vowel and dental/retroflex transcription differences retained. Forms resembling a separate direct tomato adaptation without final r are not included.')
add('f_22utxbhjyd5lu','onion','pjaj|piaz|piaj|pyaj|pias|pʸaj|pea̯j|piay|pyauj|pyæj|piu̯s|pijaj|piyaj|pʲaj|pej|pja|piaju|piazi|piyaz|pʸæj|pei̯s|pʸoj|pʸac|piajo','kannauji[p. 73];platts1884[s.v. piyāz];centralbank-saral-kannada[PDF p. 11, vegetables, item 5]','Platts p. 295 gives Persian piyāz “onion”; the visually checked Hindi table has प्याज, independently supporting the existing Hindi pyaj donor. Survey piaj/pjaj and z/j/s adaptations belong to this regional loan family. The borrowed edge identifies a provisional Hindi/Urdu route; it does not assert direct Persian contact for each target.')
add('f_6qttielo4g3ta','empty','khali','nihali-provisional2026;platts1884[s.v. ḵẖālī]','Platts p. 485 gives Arabic-derived khālī “empty, vacant, void” in Urdu/Hindi. The existing Hindi khali donor is an attested lexical form, with its provisional source label retained. Only the empty adjective is selected; no direct Arabic contact is asserted.')
add('f_yxo7nmor3lsaw','man|husband|male','mard|marad|marda|marada|marod','platts1884[s.v. mard]','Platts p. 1021 explicitly lists Persian mard and vernacular marad “man, male, husband”. The existing Hindi-Urdu mard head preserves all these senses; the separate Arabic marad obstinacy homonym is excluded.')
add('f_5plib5wmxwe6o','pestle','dasta|dasto','platts1884[s.v. dasta]','Platts p. 517 lists Persian dasta “handle, helve, haft, hilt; pestle”. The existing Hindi-Urdu dasta head therefore supports the survey pestle sense without equating it with the distinct turban-cloth or zinc homonyms.')
raw={r['ID']:r for r in json.loads((P/'inventory.json').read_text())};parents={r['ID']:r for r in csv.DictReader((ROOT/'cldf/forms.csv').open()) if r['ID'] in {q['parent'] for q in qs}};current={r['Form_ID'] for r in csv.DictReader((ROOT/'data/etymology-assignments.csv').open()) if r['Status']=='accepted' and r['Rank']=='1'};acc=[];held=[]
for rr in csv.DictReader((P/'unresearched-records.csv').open()):
 r=raw[rr['ID']]
 if r['ID'] in current or r['Language_ID']=='H' or rr['clade'] in {'Kohistani','Chitrali','Shinaic','Kunar'}:continue
 gs={g.strip().lower() for g in r['Gloss'].split(';')};w=norm(r['Form'])
 for i,q in enumerate(qs):
  if not gs<=set(q['gloss']) or w not in {norm(z) for z in q['words']}:continue
  reason=None
  if re.search('uncertain|unresolved|illegible|unreadable',r['Tags']+' '+r['Description'],re.I) and r['Language_ID']!='Rana':reason='Source uncertainty needs review before assigning the loan.'
  if reason:held.append(dict(record=r,families=[i],reason=reason,passNumber=22));continue
  d=parents[q['parent']];ev=q['evidence']+' Existing Hindi '+d['Form']+' “'+d['Gloss']+'” is the provisional donor, under the user’s preference to link supported cross-IA families. An intermediate Indo-Aryan language or another lending locality remains possible; the attestation locality is not claimed as the historical lending site.'
  if r['Language_ID']=='Rana' and 'uncertain' in r['Tags']:ev+=' RNS uncertainty concerns source locality only, as established by the earlier source audit.'
  acc.append(dict(record=r,family=i,parent=q['parent'],kind='borrowed',citation=q['citation'],evidence=ev))
(P/'loan-third-rules.json').write_text(json.dumps(qs,ensure_ascii=False,indent=1));(P/'loan-third-decisions.json').write_text(json.dumps(dict(accepted=acc,held=held),ensure_ascii=False,indent=1));(P/'loan_third_save.py').write_text((P/'sixteenth_save.py').read_text().replace('sixteenth','loan-third'))
for i,q in enumerate(qs):
 a=[x['record'] for x in acc if x['family']==i];print(q['gloss'],len(a),'; '.join(l+': '+', '.join(sorted({x['Form'] for x in a if x['Language_ID']==l})) for l in sorted({x['Language_ID'] for x in a})))
print('accepted',len(acc),'held',len(held))
