import csv,json,re,hashlib
from pathlib import Path
P=Path(__file__).resolve().parent;ROOT=P.parents[2];ledger=json.loads((P/'pass-ledger.json').read_text());done={x['record']['ID'] for f in ledger['decisionFiles'] for x in json.loads((P/f).read_text())['accepted']}
spec=[('6152','tooth','ḍaṭ|ḍaṭe',34,28,9,'CDIAL 6152 danta gives Gujarati/Marathi/Hindi dā̃t tooth. The printed source has dental d/t, matching this family.'),('5798-4','star','ṭara|ṭaro',42,36,44,'CDIAL 5798.4 tāraka gives Gujarati tāro and Hindi/Marathi tārā star. The printed source has dental t, selecting the regular western masculine branch.'),('6391','milk','ḍuḍ|ḍuḍe',52,46,91,'CDIAL 6391 dugdha gives Gujarati/Marathi dūdh and unaspirated regional dud/dūd milk. The printed source has dental d̪, including its Hindi/Gujarati/Marathi control forms.'),('10702','night','raṭ|raṭe',58,52,118,'CDIAL 10702 rātrī gives Gujarati/Marathi/Hindi rāt night. The printed source has dental final t̪.'),('10539','red','raṭo',65,59,150,'CDIAL 10539 rakta gives Gujarati rātũ, regional rato red. The printed Gomon form has dental t̪, not the retroflex stop in the stored transcription.'),('13139','seven','saṭ|haṭ|haṭe',66,60,157,'CDIAL 13139 sapta gives Gujarati/Marathi/Hindi sāt seven. The printed source has dental t̪; the Noiri/Dungra h-initial forms are compared jointly with the neighboring s-initial series, with regional transmission open.')]
rules=[dict(parent=p,gloss=g,words=ws.split('|'),physicalPage=pg,printedPage=pp,item=item,citation='CDIAL['+p.replace('-','.')+'];varghesekumar2015noira[Appendix A3, p. '+str(pp)+', item '+str(item)+']',evidence=ev) for p,g,ws,pg,pp,item,ev in spec]
acc=[];held=[];cells=[];cellindex={}
for f in (ROOT/'data/other/forms/raw_data/sil_noira_2015/manual_chunks').glob('items_*_hand_keyed.tsv'):
 for r in csv.DictReader(f.open(),delimiter='\t'):cellindex[(r['Item'],r['Site_Code'])]=r
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] in done or 'varghesekumar2015noira' not in r.get('survey_sources',[]):continue
 for i,q in enumerate(rules):
  if r['Gloss']!=q['gloss'] or r['Form'] not in q['words']:continue
  m=re.search(r'item (\d+), list (\w+)',r['Source']);c=cellindex[m.groups()];assert int(c['PDF_Page'])==q['physicalPage'] and int(c['Item'])==q['item']
  ev=q['evidence']+' Visual inspection of PDF physical p. '+str(q['physicalPage'])+' confirms dental-stop glyphs misread as ɖ/ʈ by the stored source ledger. This link follows the printed reading, not an invented retroflex sound change. Stored form '+r['Form']+' and its durable ID are preserved pending a separately audited source correction. Final -e variants are retained in the same lexical family, without assigning an unsupported grammatical category.'
  acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=ev));cells.append(dict(recordId=r['ID'],storedForm=r['Form'],sourceCell=c,verifiedDentalStops=True,physicalPage=q['physicalPage'],verification='Visual reading of the original printed page; milk control checked again at 400 dpi. Only the stop-glyph mismatch is asserted.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=held)),('verified-cells',cells)]:(P/('noira-dental-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
pdf=ROOT.parent/'tmp/pdfs/noira_2015/silesr2015_012.pdf'
report=dict(source='varghesekumar2015noira',pdf=str(pdf),pdfSha256=hashlib.sha256(pdf.read_bytes()).hexdigest(),physicalPages=[34,42,52,58,65,66],printedPages=[28,36,46,52,59,60],finding='Printed dental d̪/t̪ have been stored as retroflex ɖ/ʈ in the hand-keyed ledger and consequently as ḍ/ṭ in compiled forms. The same page 52 also has genuine retroflex ɖ in the non-IA comparison rows, visibly distinct from the dental glyph.',affectedEtymologyRecords=len(acc),sourceDataEdited=False,compiledDataEdited=False,priority='High: ingestion glyph audit needed; do not infer sound laws from these stored retroflex stops.',scopeLimit='Only the six inspected item groups are verified here. Other pages, other glyphs (including nasals), and other SIL reports require independent inspection.')
(P/'noira-dental-source-audit.json').write_text(json.dumps(report,ensure_ascii=False,indent=1)+'\n')
(P/'noira-dental-source-audit.md').write_text('# Priority: Noira dental stops misread as retroflex\n\nThe original printed dental **d̪/t̪** were stored as **ɖ/ʈ**, producing compiled **ḍ/ṭ**. This is an ingestion reading error, not evidence for a historical sound change. Physical p. 52 (printed p. 46), item 91 milk, shows dental stops in the Hindi, Gujarati, Marathi and relevant Bhil rows; genuine retroflex stops occur separately in the non-Indo-Aryan comparison rows.\n\nVerified physical pages: 34, 42, 52, 58, 65, 66; printed pages: 28, 36, 46, 52, 59, 60. These support the tooth, star, milk, night, simple red, and seven etymology links. Exact IDs and source cells are in `noira-dental-verified-cells.json`.\n\nNo lexical-source, compiled-form or identity data was changed. A source correction must follow SOURCE_INGESTION_CHECKLIST.md and reconcile durable IDs, existing links and affected artifacts. Other glyphs/pages/sources remain unverified; do not apply a global replacement.\n\nPDF SHA-256: '+report['pdfSha256']+'\n\nEtymology records linked from verified readings: '+str(len(acc))+'\n')
(P/'noira_dental_save.py').write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth','noira-dental'))
print({'accepted':len(acc),'parents':len(rules)})
