import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass238';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='5853',citation='CDIAL[5853.1]',evidence='Full CDIAL tuṇḍa subsection 1 explicitly gives Oriya tuṇḍa lips/mouth/beak and Sambalpur tũḍ mouth. The selected Adivasi Oriya tuṇḍ and Bhatri tũḍə mouth responses fit this u-vowel branch; final vowel and nasal notation remain intact. Turner treats the ultimate origin as non-Aryan, probably Munda, and allows dialectal and expressive changes. The survey neutral mouth gloss is preserved without imposing an older contemptuous register. Local transmission remains unresolved.'),dict(parent='5853-3',citation='CDIAL[5853.3]',evidence='Full CDIAL tuṇḍa subsection 3 tōṇḍa explicitly gives Prakrit toṃḍa mouth, Marathi tõḍ mouth and Konkani toṃḍa. The selected o-vowel toṇḍ/ṭõḍ/tonḍə/tõḍ-type survey mouth forms fit that specifically numbered branch. Initial t/ṭ, nasalization, final stop and vowel notation remain unchanged; Turner explicitly allows IA retroflex assimilation and dialectal or expressive variation across this family. Regional transmission is unresolved, and no remote Dravidian or Munda donor is substituted for the attested IA branch.'),dict(parent='5853-17',citation='CDIAL[5853.17]',evidence='Full CDIAL tuṇḍa subsection 17 thōttha explicitly gives Maithili thothī mouth and, in the addendum, West Pahari Kotgarhi thótti/thótthəṛ snout/mouth. Bishnupriya thota and Kului ˈtʰotʰə mouth are grouped provisionally with this non-nasal aspirated branch, preserving final vowel, aspiration and stress notation. Local transmission and expressive variation remain qualified. The separately nasal thōntha chin branch is not silently substituted, and neutral survey mouth retains its own register.')]
sets=[{'tuṇḍ','tũḍə'},{'t oṇḍ','ṭoṇḍ','ṭonḍ','ṭõḍ','tonḍə','tõd','tõḍ','toṇḍ','toṇḍi'},{'thota','ˈtʰotʰə'}]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='mouth':continue
 for i,forms in enumerate(sets):
  if r['Form'] in forms:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'));break
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare238.py').read_text());print('accepted',len(acc))
