import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass150';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='9500',citation='CDIAL[9500]',evidence='CDIAL 9500 *bhiyagna wet explicitly gives Oriya bhigā and the bhig- verb family, distinguishing the g-bearing stem from *bhiyajyate 9502. The simple bhig/big wet responses preserve that stem, with regional l-participial endings, aspiration and inflection qualified. No underlying nasal is supplied where the survey has none; the precise local transmission remains unresolved.'),dict(parent='9502',citation='CDIAL[9502]',evidence='CDIAL 9502 *bhiyajyate gets wet explicitly gives Assamese bhiziba, Bengali bhijā, Oriya bhijibā, Maithili bhijlāh wet and Bhojpuri bhījal. The survey bij/bhij/bhiz series and l-participial forms match those comparanda. Affricate/retroflex-affricate notation, aspiration, final vowels and local transmission remain qualified; no extra light verb is silently discarded.'),dict(parent='5812',citation='CDIAL[5812]',evidence='CDIAL 5812 *tinta wet explicitly gives Assamese/Bengali titā, Maithili tital/tītal wet and Hindi tītā. Simple tit/tital responses fit this family; vowel and l-inflection variation is retained and local transmission unresolved. Retroflex ṭiṭino and voiced-d extensions are not included here.'),dict(parent='9503',citation='CDIAL[9503]',evidence='CDIAL 9503 *bhiyañjati wets/is wetted explicitly gives Bhojpuri bhī̃jal and Gujarati bhĩjāvũ/bhĩjavvũ. Nasal binj/bhinj wet responses match this nasal branch, with aspiration loss, y/ai and l-participial endings qualified. They are not collapsed into the nonnasal 9502 stem; the local transmission route remains open.')]
sets=[{'bīga','bhiga','bɦiglo','bɦigəlu','bɦigɦəlo','bɦiglũ','bɦigyo','bɦigā','bɦigelu','bigḷi','bigli','biglo','bhiglo'}, {'bi̤jlʰa','bʰiḍžu','bʰidža','biḍžu','bidža','bʰizla','bʰizle','bʰijra','bʰizlo','bijla','bijlʌ','bhiḍž','biḍžel','bijila'}, {'titə','titalo','titalõ','titla'}, {'bhinjailo','binjai','binjyo','bhiṇḍž'}]
amb={'sinna','sinnā','sina','sinə','ˈsʊnːə','ˈsɪnə','ʃʊnːə','sɪnə','ʃʊnːi','sɪno'}
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[];held=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='wet':continue
 for i,forms in enumerate(sets):
  if r['Form'] in forms:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'));break
 else:
  if r['Form'] in amb:held.append(dict(record=r,families=[],reason='CDIAL 13798 snih and 13934 svinna explicitly cross-reference competing derivations of western sinnā/sinnhā wet. Short sina and regional sin/sun forms require evidence to distinguish these roots; no family selected solely from the wet gloss. This is root uncertainty, not merely uncertain cross-IA borrowing.',passNumber=150))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=held))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));print('accepted',len(acc),'held',len(held));print([(q['parent'],sum(a['family']==i for a in acc)) for i,q in enumerate(rules)])
