import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass291';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='11394',citation='CDIAL[11394]',evidence='Full varṣati explicitly gives Khowar boṣik to rain. The six bośīk/boṣīk survey responses fit this verb directly even though the elicitation gloss is rain. Preserve the source gloss and infinitive ending; do not treat it as the separate Kalasha bāṣik noun. Cross-IA transmission is qualified.'),dict(parent='11392',citation='CDIAL[11392,1]',evidence='Full varṣa section 1 explicitly gives Kalasha bāṣik, Palula bāṣ, Gawri wāṣ and Shina of Swat baṣ rain, supporting the selected northern bāṣ/baś/vaś forms. Turner notes that some Dardic forms, especially long-vowel forms, may instead continue vārṣa. Preserve that published alternative in this provisional conventional family link; do not assert that the deeper choice is settled.'),dict(parent='12088',citation='CDIAL[12088]',evidence='The full vṛṣṭi entry means rain. Bengali br śti and bɾɪʃʈi retain the diagnostic r-plus-retroflex-stop sequence and fit a learned regional continuation of that form; preserve spacing and source phonetics. Learned/cross-IA transmission is qualified rather than asserting ordinary inherited cluster development.'),dict(parent='11398',citation='CDIAL[11398]',evidence='Full varṣārātri gives regional barsāt and Gujarati barsād after Prakrit varisāratta; it explicitly records alternative derivation from or crossing with varṣartu. Western varhāt/vorsāt/vəhrāt/voharat/varhaṭ forms fit the conventional family with weakening of s and source voicing/retroflexion preserved. The published alternative and exact local sound history remain unresolved; these links do not claim exclusive descent from varṣārātri.')]
sets=[('rain',{'bośīk','boṣīk'}),('rain',{'bāṣị̄k','bāś','vaś','baś','bāṣ'}),('rain',{'br śti','bɾɪʃʈi'}),('rain',{'varhāt','vorsāt','vəhrāt','vəhərāt','vaharād','voharat','uarhaṭ','varhaṭ','varhaṭe','voharaṭ'})]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining:continue
 for i,(g,fs) in enumerate(sets):
  if r['Gloss']==g and r['Form'] in fs:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare291.py').read_text());print('accepted',len(acc))
