import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass159';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='8201-6',citation='CDIAL[8201.6]',evidence='CDIAL 8201 subsection 6 *pilīla explicitly gives Kalasha pilīlyak, Palula pilīlu and Bashkarik pilīl; Shina has ph- in the same branch. Selected long pilil forms retain that diagnostic repeated-l stem, with aspiration, vowel length and endings qualified. Turner warns of taboo variation and imperfect grouping across the overall family; local transmission remains unresolved.'),dict(parent='8201-2',citation='CDIAL[8201.2]',evidence='CDIAL 8201 subsection 2 *piphīla explicitly gives Lahnda pehlā/pehlī and Awankari pèlā/pèlī ant. Awankari/Pothwari pel/pil forms match this regional family; vowel and aspiration variation are retained and qualified. This follows the western comparison rather than assigning short pil forms everywhere to *pilīla. Exact local transmission remains unresolved.'),dict(parent='8201-5',citation='CDIAL[8201.5]',evidence='CDIAL 8201 subsection 5 *pippīḍa explicitly gives Bengali pipiṛā, Assamese piparā and Hindi pipṛā ant. Eastern pipra/pepura forms match the labial-plus-r branch with contraction, vowels and deaspiration qualified; the isolated Bengali pipʼa records an apparent reduced rhotic and is not corrected. The entry warns of taboo variation and uncertain deeper origin; local transmission is unresolved.'),dict(parent='8201',citation='CDIAL[8201]',evidence='CDIAL 8201 first branch explicitly connects Nepali kamilo ant with dissimilated kipillaka/kiulī comparanda, preferring a *kãwilo history to karmin. Majhi/Bote kamila/kimila/komila preserve that ant family with vowels and endings qualified. Possible contamination with kīṭa/kṛmi and local transmission are not resolved.'),dict(parent='3193',citation='CDIAL[3193]',evidence='CDIAL 3193 kīṭa explicitly includes Prakrit kīḍa/kīḍiyā worm/insect/ant and modern western kīṛī ant. The simple kiḍ/kiḍiyā responses fit this family with gender/number endings, vowels and retroflex notation retained. The semantic range includes ant; no source gloss is changed. Extra-v and extra-l forms are excluded pending morphology, and local transmission remains unresolved.')]
sets=[{'pīlīlak','pīlīlo','pīlīlɬ','pʰīlīl'}, {'pelī','pīla','pīlā','pʰelī','peli','pila','pili','pela','pʰili'}, {'pipra','pepura','pipʼa'}, {'kamila','kimila','komila'}, {'kiḍiyā','kiḍiā','kiḍo','kiḍyo','kiḍõ'}]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='ant':continue
 for i,forms in enumerate(sets):
  if r['Form'] in forms:
   if i==1 and r['Language_ID'] not in {'awan','poth'}:continue
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'));break
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));print('accepted',len(acc))
