import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass256';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='12774',citation='CDIAL[12774]',evidence='Full śveta explicitly gives Khowar išper and išperu white. The survey iśpirū/śpirū/iśperū responses match this direct comparison; initial vowel variation and source vowel length remain intact, with local phonetic history qualified. The distinct śvaitra entry was read and not conflated.'),dict(parent='12778',citation='CDIAL[12778]',evidence='Full śvaitra gives Punjabi setā, Jaunsari śĕttō, Kumaoni/Nepali seto and Kotgarhi śetto white. These support the selected Jaunsari/Kului white responses. Source dental/aspiration notation, stress and vowels remain intact; regional transmission and exact local aspiration history remain qualified. This is the documented regional śvaitra family rather than a spelling-only assignment to śveta.'),dict(parent='12506-3',citation='CDIAL[12506]',evidence='Full śukra entry has an unnumbered -l- extension with Prakrit sukkila/sukkilla white, Jaunsari śuklō/śuklo, Kotgarhi śúklɔ and Kumaoni/Nepali sukilo white/shining. These directly support the selected Dotyali and Jaunsari responses. The existing extension node 12506-3 is used with base-entry citation because it is not printed subsection 3. Source sibilants, laterals and vowels remain intact; local transmission is qualified.'),dict(parent='1670',citation='CDIAL[1670]',evidence='Full ujjvala lists Gawri wuzalɔ, Torwali uǰΛl, Gau ozallo, Nepali ujjar, Bhojpuri/Awadhi ujar, Gujarati ujḷũ and Marathi uj̈ḷā clear white. These support the selected regional white responses. Source affricate/fricative, rhotic/lateral, vowel, nasalization and initial-glide differences remain intact; local development and cross-IA transmission remain qualified, with no automatic claim of inheritance for every record.')]
sets=[{'iśpirū','śpirū','iśperū'},{'çetu','ʃeˈt̪ə','ʃet̪ə','ʃetʰə','ʃetʊ','ʃetʰo'},{'śukilo','sukilo','çukəḷu','śukla'},{'ūzela','ūžāl','ozal','ujero','uḍzalõ','uǰʲər'}]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='white':continue
 for i,forms in enumerate(sets):
  if r['Form'] in forms:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare256.py').read_text());print('accepted',len(acc))
