import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass280';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='10978',citation='CDIAL[10978]',evidence='Full lavaṇa gives Pali/Prakrit lavaṇa/lōṇa/lūṇa and the regional l/n-initial salt series, including Kalasha lṽŕ, Shina lōəṇ/lūəṇī, Bengali lon/lun/nūn and Marathi loṇ. These support retained lobon, reduced nasal-vowel forms, nwan/nʷãn/nõən and naṇ. Nasal loss or assimilation and local vowels remain qualified; both lobon/nun alternatives belong to this family. Cross-IA transmission is unresolved, not grounds for withholding the family link.'),dict(parent='10299',citation='CDIAL[10299]',evidence='Full mṛṣṭa explicitly gives Marathi mīṭh and Konkani mīṭa salt alongside Gujarati mīṭhũ sweet. These support western miṭhu/mitu/miṭ salt responses, preserving source aspiration and ending differences and qualifying regional transmission. Do not use 10139 miṣṭa mixed: its full article has no salt evidence, despite a misleading parsed salt comparandum under it.'),dict(parent='5958',citation='CDIAL[5958]',evidence='Full taila gives widespread tel/tēl oil, Oriya tela and northwestern reflexes. This supports telo, Dang ṭʲal and both Bshk tel/tāīl alternatives, preserving local vowels/palatalization with transmission qualified.'),dict(parent='4782',citation='CDIAL[4782]',evidence='Full cikkaṇa gives Oriya cikaṇa/cikaṇā oil or ghee, Bihari ciknā oil seeds/ghee, Assamese sikaṇ smooth and Bengali cikan. Eastern cikən/cikon/cikoṇ/sikon oil responses fit this documented adjective-to-oil family; retain the local affricate/sibilant realization and qualify cross-IA transmission.')]
sets=[('salt',{'lobon','lọ̃','lụ','lā̃ū̃','lāū̃','nõən','nwan','nʷãn','naṇ','lobon / nun','lɔbon / nun'}),('salt',{'miṭhu','mitu','miṭ'}),('oil',{'tel / tāīl','telo','ṭʲal'}),('oil',{'sikon','cikən','cikon','cikoṇ'})]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining:continue
 for i,(g,fs) in enumerate(sets):
  if r['Gloss']==g and r['Form'] in fs:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare280.py').read_text());print('accepted',len(acc))
