import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass253';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='3083',citation='CDIAL[3083]',evidence='Full CDIAL kāla explicitly gives Sindhi kāro, West Pahari kāo/kāwo, Maithili kariyā, Hindi kālā/kāliyā, Marwari kāḷo, Gujarati kāḷũ/kāḷiyũ and Marathi kāḷā black. The selected survey kāl-/kar-/kaw- variants and ordinary -iya/final-vowel forms fit this regional family, preserving vowels, gemination, lateral/rhotic/stop notation and local secondary lateral syllables. Those secondary forms are family assignments, not new ancient suffix reconstructions. Cross-IA transmission and local phonetic/ending histories remain qualified; full same-family slash responses retain all variants. Turner’s possible Dravidian origin is not replaced by a new donor claim.')]
forms={'kāl / kāo / kāṛo','kāo / qāṛo','qāo / qāṛo','kaḍa','kaḍo','kãḍo','kalia','koḷa','kərea','kəliya','kaṛiya','kʌliya','kʌṛiya','kella','kelua','keluh','keluua','keriye','kavu','kaḷːa','kāḷḷo','kāḷlo','kāḷalo','kāḷəḷũ','kāḷlə','kaḷəḷu','kalũ','kāvu','kaalːo','kāvvo','kaya','kalya','kadia','kolia','kau','kawɸo','kaḍu','ˈkaː','kaɭai','kaː','kallo','kaiyo','kalu','kalːo'}
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[];held=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining:continue
 if r['Gloss']=='black' and r['Form'] in forms:
  q=rules[0];acc.append(dict(record=r,parent=q['parent'],family=0,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
 elif r['Gloss']=='yellow' and r['Form'] in {'hilda','hildi','hildiya','hildu','ildu','holud'}:held.append(dict(record=r,families=[],passNumber=253,reason='Full haridra 13990 explicitly gives colour forms such as halidda/haḷadiā/haldiyā, while haridrā 13992 separately gives Bengali halud/haldi turmeric and hāridra turmeric-coloured. These Hajong/Bengali yellow forms plausibly belong to that group, but a direct local adjective or derivation is needed to choose the colour stem versus turmeric-based formation. Current parsed links disagree between the two entries. Do not decide the parent solely from the yellow gloss or from uncertain IA transmission.'))
 elif r['Gloss']=='yellow' and r['Form'] in {'andi','ondi','ordi'}:held.append(dict(record=r,families=[],passNumber=253,reason='Bishnupriya andi/ondi/ordi yellow was compared with full haridra/haridrā colour and turmeric entries, but no direct Bishnupriya comparison establishes the h/l loss or nasal/rhotic pattern, nor which historical stem is appropriate. This remains a tentative colour-family lead requiring local dictionary evidence, not an accepted turmeric derivation.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=held))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare253.py').read_text());print('accepted',len(acc),'held',len(held))
