import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass248';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='f_sttfx62nfksli',citation='arora;platts1884[366]',evidence='The existing regional ṭhēhunā knee/elbow family is registered in extensions_ia.csv e82 and includes Chitwan ṭhehun knee. Independently, full Platts p.366 gives ṭhewnā/ṭheʼonā/ṭheʼunā knee and nasalized variants. The selected Danuwar/Tharu knee responses are grouped provisionally in this regional family, preserving medial h, vowels, nasalization and final ī/u/a. This is family membership only: it does not establish the starred head as an ancient reconstruction or adopt Platts’s aṣṭhīvan derivation. Earlier elbow-semantic concerns remain separate; these responses mean knee. Regional IA transmission remains unresolved.'),dict(parent='4479-2',citation='CDIAL[4479.2]',evidence='Full CDIAL ghuṭa subsection 2 ghuṇṭa explicitly gives Kumaoni ghuno knee, Nepali ghũṛo and Gujarati ghũṭaṇ knee. Dotyali gũṇā̃/ghuṇā/ghũṇā/ghudā and Majhi/Bote ghõḍa/ghõra/ghũḍa/ghora knee fit this nasal regional branch, with source aspiration, nasalization, retroflex stop/rhotic and final-vowel notation preserved and qualified. The separately numbered ghuṭṭa Hindi ghuṭnā branch is not substituted merely on the knee gloss. Regional IA transmission and local phonetic developments remain unresolved.')]
sets=[{'tʰeuna','ṭʰeuna','ṭʰehun','ṭhyhun','ṭehuni','ṭhyahuni','thĩhun'},{'gũṇā̃','gʰuṇā','gʰũṇā','gʰudā','gʰõḍa','gʰõra','gʰũḍa','gʰora'}]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='knee':continue
 for i,forms in enumerate(sets):
  if r['Form'] in forms:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'));break
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
a=json.loads((P/(stem+'-primary-articles.json')).read_text());q=next(q for q in json.loads((P/'pass104-second-platts-research.json').read_text()) if '31)' in q.get('text','') and 'ṭhewnā' in q.get('text',''));a['platts1884']=[dict(page=366,url=q.get('url',''),text=q['text'][q['text'].index('29)'):])];(P/(stem+'-primary-articles.json')).write_text(json.dumps(a,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'-family-evidence.json')).write_text(json.dumps(dict(regionalHead='f_sttfx62nfksli',sourceRow='data/other/params/extensions_ia.csv e82',existingAttestation='f_aizbmf3tnutre Chitwan ṭhehun knee, boehm',earlierResearch='pass104-research-notes.md',claim='regional lexical family only, ultimate ancestry not asserted'),ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare248.py').read_text());print('accepted',len(acc))
