import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass263';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='3949',citation='CDIAL[3949]',evidence='Full gakṣa gives Nepali/Bengali gāch, Assamese gās, Oriya gacha and Maithili gachiā tree. These support selected eastern affricate/sibilant tree forms and ordinary vowel endings. Source aspiration, nasalization and vowels remain intact; exact local developments and cross-IA transmission remain qualified. The grove senses of some gāchī comparanda do not change the survey tree gloss.'),dict(parent='5362',citation='CDIAL[5362.1]',evidence='Full jhāṭa subsection 1 explicitly gives Gujarati jhāṛ tree/plant, Marathi jhāḍ tree and Hindi chāṛ bush alongside regional sibilant forms. These support the selected simple western jhaḍ/saḍ/chāḍ tree forms. Source affrication, sibilants, aspiration, retroflexion and final inflection remain intact; local phonetic history and cross-IA transmission remain qualified. No new Munda donor is asserted from Turner’s ultimate-origin suggestion.'),dict(parent='9297-2',citation='CDIAL[9297.2]',evidence='Full būṭa subsection 2 būṭṭa explicitly lists Lahnda/Punjabi būṭā and West Pahari buṭṭ/būṭā tree, plus Kotgarhi bvṭṭi plant/tree. This supports selected northern u-vowel tree responses and their ordinary inflection. Source dental/retroflex notation, nasalization and vowels remain intact; local transmission is qualified. Distinct o-vowel and aspirated-head branches are not automatically conflated.'),dict(parent='9297-3',citation='CDIAL[9297.3]',evidence='Full būṭa subsection 3 bōṭṭa explicitly gives West Pahari boṭṭ and Kumaoni/Nepali boṭ tree/stem/trunk. The selected Danuwar and Kului boṭ/botːe/botːiː tree forms match this o-vowel branch. Source gemination, vowels and inflection remain intact, with local development and cross-IA transmission qualified.')]
sets=[{'gʰãts','gʰats','gʰaci','gatśʰ','gʰacʰ','gʰasi','gʰac','gācʰī','gāīcʰ','goc'},{'dzaḍ','dzɦaḍ','jɦəhāḍ','zāṛə','jad','sāḍ','chāḍ','dzɦār','saḍi','saṛ','saḍe','saṛe','saḍ','dzʱaḍ','dzhaḍ'},{'būtā','būta','bū̃ṭõ / būṭo','bū̃ṭõ','būto','buta','buto','buṭo','budo','buṭ'},{'boṭ','botːe','botːiː'}]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='tree':continue
 for i,fs in enumerate(sets):
  if r['Form'] in fs:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare263.py').read_text());print('accepted',len(acc))
