import json,csv
from pathlib import Path
P=Path(__file__).resolve().parent;stem='pass112';assert not (P/(stem+'-decisions.json')).exists()
evidence={'10286':'CDIAL 10286 mṛttikā gives Kumauni māṭo/māṭi and Nepali māṭo, eastern māṭi earth/clay. Dotyali məṭi retains the retroflex and final i with a central first vowel; this soil response belongs with the earth family.', '6261':'CDIAL 6261 *dādda explicitly gives Nepali dājyu elder brother. Dotyali dāju fits with loss of the palatal glide; the source length is preserved. This is a nursery kinship family.', '10055':'CDIAL 10055 māma gives Nepali/Hindi māmā and Prakrit māma mother’s brother. Kochila Tharu məmə fits with central vowels. The elicited seniority is contextual and is not reconstructed for the ancestor; the dictionary identifies a nursery formation.', '4560':'CDIAL 4560 cakṣus gives Bengali cok(h)/cauk eye and Prakrit cakkhu. Bengali tʃok is the corresponding affricate transcription. Turner marks the eastern forms probably borrowed from Prakrit, so this family link retains that historical qualification.', '986':'CDIAL 986 asmad gives Prakrit amhe and Hindi/Bhojpuri ham, Gujarati ame we. Bhili hamũ fits the plural-pronoun family with final nasal vowel retained; exclusivity is an elicited local distinction, not a reconstructed property of asmad.', '12459':'CDIAL 12459.1 śilā gives Oriya siḷa stone/grinding stone, Bengali sil and Assamese xil. Adivasi Oriya sil stone fits the single-l branch, retaining final-vowel loss; the doubled *śillā subsection is not selected.', '9459':'CDIAL 9459 bhāra gives Punjabi/Lahnda bhārā heavy and western Pahari bhārā. Dogri pārə fits the regional devoiced onset and final schwa alongside those adjective forms. The onset comparison is regional, not an assertion that Turner quotes this exact Dogri response.'}
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};inventory={r['ID']:r for r in json.loads((P/'inventory.json').read_text())}
rules=[dict(parent=p,citation='CDIAL['+p+('.1' if p=='12459' else '')+']',evidence=e+' Local Indo-Aryan transmission remains unresolved.') for p,e in evidence.items()];indices={r['parent']:i for i,r in enumerate(rules)};acc=[]
for x in json.loads((P/'pass108-expansion-candidates.json').read_text()):
 p=x['parents'][0];rid=x['record']['ID']
 if p not in indices or rid not in remaining:continue
 i=indices[p];q=rules[i];r=inventory[rid];acc.append(dict(record=r,parent=p,family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
for name,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+name+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));print(len(acc))
