import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass251';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='14152',citation='CDIAL[14152]',evidence='Full CDIAL hṛdaya heart explicitly gives Gawri hiṛa, Kalasha hīṛa/hṛiya, Phalura hiṛo, Torwali huī, Lahnda hā̃, eastern hiyā and western hiya/hīyo. The selected reduced heart forms fit these regional comparisons, preserving vowels, rhotic loss, h loss, nasalization and final glide/inflection. The conservative hraday/hīrday/hrɛday-type forms are included with learned or cross-IA transmission unresolved; source spacing and phonetics remain unchanged. The heart sense is directly documented and not inferred from unrelated kidney or lung terms.'),dict(parent='6914',citation='CDIAL[6914.1]',evidence='Full CDIAL nakha subsection 1 explicitly gives nasal early variants such as Domaaki naṅ and Phalura nāṅg/nōṅg, eastern Nepali naṅ, and Punjabi nahũ/Maithili nauh/Bhojpuri nõh. Buksa nũɡ and Dang nuhũ nail fit this regional nasal family with source vowels, final g and aspiration preserved. Local transmission and the precise nasal development are qualified rather than assigned a new intermediate reconstruction.'),dict(parent='6914-2',citation='CDIAL[6914.2]',evidence='Full CDIAL nakha subsection 2 nakkha explicitly gives Bshk nakh, Savi nakē and Torwali nōkh. Selected Bshk naī̃k/nūk/nāk and Mai nākh forms follow that regional branch; Oriya no.kʰo and Vasavi nakhõ are provisionally grouped with the retained velar-aspirate family. Source nasalization, vowels, h loss or retention and punctuation remain intact; local transmission and the historical geminate are qualified. The complete repeated-form slash response is preserved. Longer -ḍo/-ḍio nail forms remain separate.')]
sets=[{'hraday','ardaī','hɛrdav','hrɛday','hīrday','həṛudaio','ruḍay','hị̄a','hẹ̃','hiṛo','heṛé','hā̃','haī','hiv','iya'}, {'nũɡ','nuhũ'}, {'naī̃k','nūk / nāk','nākʰ / nākʰ','no.kʰo','nakhõ'}];glosses=['heart','nail','nail']
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining:continue
 for i,forms in enumerate(sets):
  if r['Gloss']==glosses[i] and r['Form'] in forms:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'));break
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare251.py').read_text());print('accepted',len(acc))
