import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass258';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='3585-2',citation='CDIAL[3585.2]',evidence='Full kravya entry specifically separates subsection 2 kraviya and gives Khowar krui red, bloodshot, reddish brown, auburn, crimson. This directly supports the survey krūī and epenthetic/rhotic variants, including complete same-family slash responses. Source vowels, rhotics and length remain unchanged, with exact local phonetic history and transmission qualified.'),dict(parent='11165',citation='CDIAL[11165]',evidence='Full lohita explicitly gives Bshk lōu red, alongside regional lōya/ləwī/luhī red. The selected Bshk lov/laū/laʔū responses match that direct red comparison. Source vowel, glide and glottal notation remain intact. Turner reports an alternative lohuta analysis in the comparison; the link records the documented lohita family with that historical uncertainty retained, not a newly proven intermediate reconstruction.'),dict(parent='11168',citation='CDIAL[11168]',evidence='Full lohila explicitly gives Palula lohílu/lᵊhōilo and Shina Kohistani līlṷ, Palesi līlo red. This supports the Palula lohīḷū and Chil/Gowro lhīlū survey colour forms. The latter shortened i-vowel forms are compared with the documented nīla crossing; no independent local crossing event is asserted. Source h, lateral quality and vowels remain intact; local history and cross-IA transmission remain qualified.')]
sets=[{'kūṛūī','krūī','kiṛūī','kroī','krūī / kiṛūī','kṛūī / kiṛūī'},{'lov','laū','laʔū'},{'lohīḷū','lhīlū'}];remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[];held=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='red':continue
 for i,fs in enumerate(sets):
  if r['Form'] in fs:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
 if r['Form'] in {'logūr','lahūr'}:held.append(dict(record=r,families=[2],passNumber=258,reason='Full lohila article appends Torwali lohūr/laūr red with a tentative lohuṭa derivation, rather than securely deriving it from lohila. Survey logūr/lahūr therefore needs the exact parent/extension resolved; the uncertainty is not solely cross-IA transmission.'))
 elif r['Form']=='lo / lohīḷū':held.append(dict(record=r,families=[1,2],passNumber=258,reason='The full mixed response combines short lo and directly supported lohila-type lohīḷū. Full lohita also supplies short red forms; a single parent cannot be assigned to the whole response without establishing the short variant’s family or representing alternatives correctly.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=held))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare258.py').read_text());print('accepted',len(acc),'held',len(held))
