import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass240';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='13952',citation='CDIAL[13952]',evidence='Full CDIAL haḍḍa explicitly gives Punjabi/Hindi haḍḍī, Gujarati/Marathi hāḍ and, in the addendum, Kotgarhi hàṛkɔ, Jaunsari hāḍkī and Garhwali hāḍgu with a hāḍku comparison. The selected simple and k-extended bone forms fit this documented family; vowels, voicing, retroflexion, optional h, nasalization and inflection remain as elicited. The medial k extension is directly attested, not reconstructed from the survey alone. Turner calls the connection with asthi/aṣṭhi very doubtful; no such deeper ancestry is asserted. Regional IA transmission remains unresolved.'),dict(parent='13952',citation='CDIAL[13952]',evidence='Full CDIAL haḍḍa explicitly gives Phalura haḍḍuṅg bone. Phal survey haḍūŋk fits this exact regional extended form with source vowel length, nasal notation and final k/g voicing retained. Regional transmission and the internal history of the extension remain qualified; the entire response is linked rather than treating ūŋk as an independently established component.'),dict(parent='13952',citation='CDIAL[13952]',evidence='Full CDIAL haḍḍa explicitly gives Kashmiri aḍa bones, eastern Assamese hār/Bengali hāṛ/Oriya hāṛa and feminine haḍḍī bone in Hindi/Punjabi. The selected eastern aṛa/ar and Adivasi Oriya āḍi/āṛi/aṛi/haṛi/aḍi bone forms are grouped with this regional family, with h loss, rhotic versus stop spelling and final vowels preserved. This does not assert a Kashmiri loan to eastern languages. Regional history remains qualified, and the doubtful asthi comparison is not adopted.')]
sets=[{'hʌɽːi','haḍko','hāṛəko','haṭəko','hāṭkũ','haṭkũ','haṭkā','hāṭkā','hāṭkõ','hāḍuk','haḍəke','ˈhəɖokə','həɖokə','haɖokʰə','(h)əɖokə','(h)əɖikeː','əɖəkə','əɖiko','haḍḍe','haḍəkka','haṛika'}, {'haḍūŋk'}, {'aṛa','ar','āḍi','āṛi','aṛi','haṛi','aḍi'}]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining or r['Gloss']!='bone':continue
 for i,forms in enumerate(sets):
  if r['Form'] in forms:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'));break
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare240.py').read_text());print('accepted',len(acc))
