import csv,json
from pathlib import Path
P=Path('/Users/aryamanarora/Documents/Code/jambu-all/data/curation/etymology-lab/indo-aryan-sil-20260914');stem='pass307';assert not (P/(stem+'-decisions.json')).exists()
rules=[dict(parent='1577',citation='CDIAL[1577]',evidence='Full indradhanus gives rainbow and Pali indradhanu, Prakrit imdadhanu/imdahanu. The selected eastern Indra-dhanu forms preserve both lexical elements with regional cluster simplification, vowel variation, and source d/dh or retroflex transcription retained. Learned or cross-IA transmission remains qualified.'),dict(parent='1577',citation='CDIAL[1577]',evidence='Full indradhanus explicitly gives Khowar dronhanu, with alternative explanations: crossing with dron < drona or descent from proposed dronadhanuka. The selected drohan/drnhanu/dronhanu belong to this published rainbow comparison; retain both alternatives and do not claim uncomplicated inheritance from indradhanus.'),dict(parent='1577',citation='CDIAL[1577]',evidence='Full indradhanus gives Palula izdran/izran with expressly unexplained z/zh, Bshk idran, and Tor inhan. These support selected ziran/drani and hinan/hidan/hirdan/hedon rainbow forms, preserving survey metathesis, rhotic loss or h-placement as qualified local developments. The link asserts the comparative family, not a proven regular sound derivation; opaque higdān and mixed responses excluded.'),dict(parent='1577',citation='CDIAL[1577];CDIAL[14295]',evidence='Turner addendum 14295 to indradhanus explicitly gives Shina bizon rainbow crossed with vidhra. The selected neighbouring Indus Kohistani/Chilisso bizon/bizon/bizvan forms closely match this published crossed family. Preserve vowel/sibilant differences and the crossing qualification; inheritance versus cross-IA transmission remains unresolved, and no direct Shina donor is asserted.')]
sets=[('rainbow',{'indor dun','indṛo danasə','inḍreḍenuś','inḍreḍhenuṣ','inḍreḍhenuś','indor donu','indordonu','indordvnu','indro donu'}),('rainbow',{'drohān','drnhānū','dronhānū'}),('rainbow',{'zirān','drāṇī','hīnān','hīdān','hīrdān','hedõʔ'}),('rainbow',{'bīžon','bīžoṇ','bīzvāṇ','bīžōn'})]
remaining={r['ID'] for r in csv.DictReader((P/'unresearched-records.csv').open())};acc=[]
for r in json.loads((P/'inventory.json').read_text()):
 if r['ID'] not in remaining:continue
 for i,(g,fs) in enumerate(sets):
  if r['Gloss']==g and r['Form'] in fs:
   q=rules[i];acc.append(dict(record=r,parent=q['parent'],family=i,kind='reflex',citation=q['citation'],evidence=q['evidence']+' Exact response: '+r['Form']+'.'))
for suffix,obj in [('rules',rules),('decisions',dict(accepted=acc,held=[]))]:(P/(stem+'-'+suffix+'.json')).write_text(json.dumps(obj,ensure_ascii=False,indent=1)+'\n')
(P/(stem+'_save.py')).write_text((P/'global_sixteenth_save.py').read_text().replace('global-sixteenth',stem));(P/(stem+'_prepare.py')).write_text(Path('/tmp/prepare307.py').read_text());print('accepted',len(acc))
